# Generated by Django 3.2.12 on 2022-04-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='wife',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oto.author'),
        ),
        migrations.AlterField(
            model_name='wife',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
    ]
