# Generated by Django 3.2.12 on 2022-04-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oto', '0006_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='images/Clipboard_20220412.png', upload_to='images/'),
            preserve_default=False,
        ),
    ]
