Object.defineProperty(exports, "__esModule", {
    value: !0
});

var SELECT_CONCAT = exports.SELECT_CONCAT = "SELECT_CONCAT", CONCAT_LIST = exports.CONCAT_LIST = "CONCAT_LIST", SELECTED_CONCAT = exports.SELECTED_CONCAT = "SELECTED_CONCAT", REST_SELECTED_CONCAT = exports.REST_SELECTED_CONCAT = "REST_SELECTED_CONCAT";