# Generated by Django 3.2.12 on 2022-04-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_banner_bindphone_complainimage_complainlist_imageupload_member_order_pictureinfo_shoplist_statistica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplainImage',
        ),
        migrations.DeleteModel(
            name='ComplainList',
        ),
    ]
