# Generated by Django 3.2.12 on 2022-04-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_shoplist_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='area_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shoplist',
            name='shop_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
