# Generated by Django 3.2.12 on 2022-04-14 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20220414_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopList',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='店铺ID')),
                ('area_id', models.IntegerField()),
                ('area_name', models.CharField(max_length=64)),
                ('area_size', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('city_name', models.CharField(max_length=64)),
                ('consultant_count', models.CharField(max_length=64)),
                ('consultant_list', models.TextField()),
                ('consultants_numbers', models.CharField(max_length=64)),
                ('is_new', models.IntegerField()),
                ('is_recommend', models.IntegerField()),
                ('lable_ids', models.CharField(max_length=64)),
                ('lable_list', models.TextField()),
                ('province_id', models.IntegerField()),
                ('province_name', models.CharField(max_length=64)),
                ('rent_money', models.IntegerField()),
                ('shop_type', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('transfer_fee', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商铺列表',
                'verbose_name_plural': '商铺列表',
                'db_table': 'polls_shop_list',
            },
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='shop/', verbose_name='图片')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.shoplist', verbose_name='商铺')),
            ],
            options={
                'verbose_name': '商铺图片',
                'verbose_name_plural': '商铺图片',
                'db_table': 'polls_shop_image',
            },
        ),
    ]
