# Generated by Django 3.2.12 on 2022-04-14 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(default='', max_length=255)),
                ('image_src', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banner',
                'db_table': 'polls_banner',
            },
        ),
        migrations.CreateModel(
            name='BindPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=11)),
                ('create_time', models.DateField()),
                ('update_time', models.DateField()),
            ],
            options={
                'verbose_name': '绑定手机号',
                'verbose_name_plural': '绑定手机号',
                'db_table': 'polls_bind_phone',
            },
        ),
        migrations.CreateModel(
            name='ComplainList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('complainTel', models.CharField(max_length=11)),
                ('complainContent', models.CharField(max_length=255)),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '投诉列表',
                'verbose_name_plural': '投诉列表',
                'db_table': 'polls_complain_list',
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.ImageField(upload_to='img/')),
            ],
            options={
                'verbose_name': '图片上传',
                'verbose_name_plural': '图片上传',
                'db_table': 'polls_imageupload',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechatID', models.CharField(max_length=255, verbose_name='微信ID')),
                ('phoneNumber', models.CharField(max_length=255, verbose_name='手机号')),
                ('renewPoint', models.IntegerField(default=0, verbose_name='消费刷新点')),
                ('isPublished', models.IntegerField(default=0, verbose_name='是否发过店铺')),
                ('createTime', models.DateTimeField(default=0, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(default=0, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员',
                'db_table': 'polls_member',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechatID', models.IntegerField(default=0, verbose_name='微信ID')),
                ('orderType', models.CharField(max_length=20, verbose_name='订单类型')),
                ('orderNumber', models.CharField(default=0, max_length=255, verbose_name='订单号')),
                ('wechatOrderNumber', models.CharField(default=0, max_length=255, verbose_name='微信订单号')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('orderAmount', models.IntegerField(default=0, verbose_name='订单金额')),
                ('payAmount', models.IntegerField(default=0, verbose_name='支付金额')),
                ('renewPoint', models.IntegerField(default=0, verbose_name='消费刷新点')),
                ('syncStatus', models.CharField(max_length=20, verbose_name='是否同步')),
                ('refundAmount', models.IntegerField(default=0, verbose_name='退款金额')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'polls_order',
            },
        ),
        migrations.CreateModel(
            name='PictureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 'polls_pictureinfo',
            },
        ),
        migrations.CreateModel(
            name='Statistical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_shop', models.IntegerField(default=0)),
                ('find_shop_yesterday', models.IntegerField(default=0)),
                ('is_redirect', models.IntegerField(default=0)),
                ('login_num', models.IntegerField(default=0)),
                ('login_num_yesterday', models.IntegerField(default=0)),
                ('transfer_shop', models.IntegerField(default=0)),
                ('transfer_shop_yester', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '统计',
                'verbose_name_plural': '统计',
                'db_table': 'polls_statistical',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '测试',
                'verbose_name_plural': '测试',
                'db_table': 'polls_test',
            },
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '提示消息',
                'verbose_name_plural': '提示消息',
                'db_table': 'polls_tips',
            },
        ),
        migrations.CreateModel(
            name='ShopList',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=64)),
                ('area_size', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('city_name', models.CharField(max_length=64)),
                ('consultant_count', models.CharField(max_length=64)),
                ('consultant_list', models.TextField()),
                ('consultants_numbers', models.CharField(max_length=64)),
                ('shop_id', models.IntegerField()),
                ('is_new', models.IntegerField()),
                ('is_recommend', models.IntegerField()),
                ('lable_ids', models.CharField(max_length=64)),
                ('lable_list', models.TextField()),
                ('province_id', models.IntegerField()),
                ('province_name', models.CharField(max_length=64)),
                ('rent_money', models.IntegerField()),
                ('shop_type', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('transfer_fee', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('type_name', models.DateField(max_length=64)),
                ('shop_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.test')),
            ],
            options={
                'verbose_name': '商铺列表',
                'verbose_name_plural': '商铺列表',
                'db_table': 'shop_list',
            },
        ),
        migrations.CreateModel(
            name='ComplainImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='complain/', verbose_name='图片')),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.complainlist', verbose_name='投诉')),
            ],
            options={
                'verbose_name': '投诉图片',
                'verbose_name_plural': '投诉图片',
                'db_table': 'polls_complain_image',
            },
        ),
    ]
