# Generated by Django 3.2.12 on 2022-04-14 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220414_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('complainTel', models.CharField(max_length=11)),
                ('complainContent', models.CharField(max_length=255)),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '投诉列表',
                'verbose_name_plural': '投诉列表',
                'db_table': 'polls_complain_list',
            },
        ),
        migrations.CreateModel(
            name='ComplainImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='complain/', verbose_name='图片')),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.complainlist', verbose_name='投诉')),
            ],
            options={
                'verbose_name': '投诉图片',
                'verbose_name_plural': '投诉图片',
                'db_table': 'polls_complain_image',
            },
        ),
    ]
