# Generated by Django 3.2.12 on 2022-04-14 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_complainimage_complainlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='shop/', verbose_name='图片')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.shoplist', verbose_name='商铺')),
            ],
        ),
    ]
