# Generated by Django 3.2.12 on 2022-04-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_shoplist_shop_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplist',
            name='type_name',
        ),
        migrations.AddField(
            model_name='shoplist',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=2022, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoplist',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
