# Generated by Django 3.2.12 on 2022-04-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20220414_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplist',
            name='createTime',
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='updateTime',
        ),
    ]
