# Generated by Django 3.2.12 on 2022-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20220414_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplist',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=2022, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
