# Generated by Django 3.2.12 on 2022-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_shoplist_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='createTime',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
