# Generated by Django 3.2.12 on 2022-04-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20220414_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopImage',
        ),
    ]
