# Generated by Django 3.2.12 on 2022-04-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_shopimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopImage',
        ),
    ]
