# Generated by Django 3.2.12 on 2022-04-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_shopimage_shoplist'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommentUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=64)),
                ('user_phone', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '推荐人',
                'verbose_name_plural': '推荐人',
                'db_table': 'polls_recomment_user',
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='BindPhone',
        ),
        migrations.RemoveField(
            model_name='complainimage',
            name='complain',
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='PictureInfo',
        ),
        migrations.RemoveField(
            model_name='shopimage',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Statistical',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Tips',
        ),
        migrations.DeleteModel(
            name='ComplainImage',
        ),
        migrations.DeleteModel(
            name='ComplainList',
        ),
        migrations.DeleteModel(
            name='ShopImage',
        ),
        migrations.DeleteModel(
            name='ShopList',
        ),
    ]
