# Generated by Django 3.2.12 on 2022-04-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20220425_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recommentUser',
        ),
    ]
