# Generated by Django 3.2.12 on 2022-04-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0020_delete_recommentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommentUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=64)),
                ('user_phone', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '推荐人',
                'verbose_name_plural': '推荐人',
                'db_table': 'polls_recomment_user',
            },
        ),
    ]
