# Generated by Django 3.2.12 on 2022-04-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oto', '0002_auto_20220413_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('author', models.ManyToManyField(to='oto.Author')),
            ],
        ),
    ]
